# Generated by Android Studio
# This file is intentionally left mostly empty.
# Add project wide ProGuard rules here.
-keepclassmembers class com.videoplayer.app.MainActivity$AndroidBridge {
   public *;
}
